import { defineStore } from 'pinia';
import { ref, computed } from 'vue';

export const useLanguageStore = defineStore('language', () => {
    const currentLocale = ref(localStorage.getItem('locale') || 'en');

    const locales = {
        en: {
            name: 'English',
            flag: '🇺🇸',
            code: 'en'
        },
        gu: {
            name: 'ગુજરાતી',
            flag: '🇮🇳',
            code: 'gu'
        }
    };

    const translations = ref({
        en: {
            dashboard: 'Dashboard',
            documents: 'Documents',
            recipients: 'Recipients',
            analytics: 'Analytics',
            subscription: 'Subscription',
            settings: 'Settings',
            users: 'Users',
            sign_out: 'Sign out',
            new_document: 'New Document',
            notifications: 'Notifications',
            search: 'Search',
            welcome_back: 'Welcome back',
            admin: 'Admin',
            super_admin: 'Super Admin',
            member: 'Member',
            village_name: 'Village Name',
            recipient_name: 'Recipient Name',
            edit_document: 'Edit Document',
            create_document: 'Create Document',
            home: 'Home',
            publish_document: 'Publish Document',
            save_as_draft: 'Save as Draft',
            back_to_editor: 'Back to Editor',
            review_confirm: 'Review & Confirm',
            details: 'Details',
            upload: 'Upload',
            fields: 'Fields',
            review: 'Review',
            name_your_document: 'Name your document',
            document_title: 'Document title',
            description: 'Description',
            continue: 'Continue',
            cancel: 'Cancel',
            drop_files_here: 'Drop files here',
            choose_files: 'Choose files',
            uploaded_document: 'Uploaded document',
            add_fields: 'Add Fields',
            placed_fields: 'Placed Fields',
            width: 'Width',
            height: 'Height',
            color: 'Color',
            language_selection: 'Language Selection',
            add_recipient: 'Add Recipient',
            edit_recipient: 'Edit Recipient',
            import_recipients: 'Import Recipients',
            export: 'Export',
            search_recipients: 'Search recipients...',
            all_recipients: 'All Recipients',
            active: 'Active',
            inactive: 'Inactive',
            name: 'Name',
            village: 'Village',
            phone: 'Phone',
            actions: 'Actions',
            edit: 'Edit',
            delete: 'Delete',
            save_changes: 'Save Changes',
            total_recipients: 'Total Recipients',
            links_sent: 'Links Sent',
            pending: 'Pending',
            sent: 'Sent',
            all_villages: 'All Villages',
            opening: 'Opening...',
            from_contacts: 'From Contacts',
            recent_activity: 'Recent Activity',
            view_all: 'View All',
            status: 'Status',
            selected: 'selected',
            send_whatsapp_all: 'Send WhatsApp to All',
            generate_links: 'Generate Links',
            delete_selected: 'Delete Selected',
            update_recipient: 'Update Recipient',
            total_documents: 'Total Documents',
            in_progress: 'In Progress',
            completed: 'Completed',
            drafts: 'Drafts',
            search_documents: 'Search documents...',
            all_statuses: 'All statuses',
            draft: 'Draft',
            expired: 'Expired',
            title: 'Title',
            progress: 'Progress',
            date: 'Date',
            no_description: 'No description',
            no_documents_found: 'No documents found',
            create_first_document: 'Create your first document to start.',
            delete_document: 'Delete Document',
            action_cannot_undone: 'This action cannot be undone',
            view: 'View',
            create: 'Create',
            document_name_desc: 'Give your document a clear title for easy tracking.',
            optional: 'optional',
            description_placeholder: 'Add some context for this document...',
            upload_desc: 'or click to browse — PDF or Images supported',
            uploaded: 'Uploaded',
            page: 'PAGE',
            add_fields_desc: 'Click on the document to place fields where recipients should provide their information.',
            preparing: 'Preparing...',
            download: 'Download',
            access_denied: 'Access Denied',
            expired_link_desc: 'This invitation link has expired or the security token is invalid. Please contact the sender for a new link.',
            go_to_homepage: 'Go to Homepage',
            personal_invitation: 'Personal Invitation',
            loading_invitation: 'Loading your invitation...',
            document_unavailable: 'Document unavailable.',
            namaste: 'Namaste',
            invited_from: 'You have been invited to join us from',
            analytics_desc: 'Track your invitation performance',
            last_7_days: 'Last 7 days',
            last_30_days: 'Last 30 days',
            last_90_days: 'Last 90 days',
            documents_created: 'Documents Created',
            links_generated: 'Links Generated',
            whatsapp_sent: 'WhatsApp Sent',
            email_sent: 'Email Sent',
            links_generated_over_time: 'Links Generated Over Time',
            links: 'Links',
            whatsapp: 'WhatsApp',
            top_documents: 'Top Documents',
            delivery_channels: 'Delivery Channels',
            village_breakdown: 'Village Breakdown',
            admin_greeting: 'Welcome back, Admin!',
            dashboard_subtitle: "Here's what's happening with your invitations today.",
            recent_documents: 'Recent Documents',
            manage_subscription: 'Manage Subscription',
            upload_template: 'Upload Template',
            add_new_document: 'Add new document',
            add_recipients: 'Add Recipients',
            edit_recipients: 'Edit Recipients',
            manage_your_list: 'Manage your list',
            send_via_whatsapp: 'Send via WhatsApp',
            share_invitations: 'Share invitations',
            view_analytics: 'View Analytics',
            track_performance: 'Track performance',
            import_desc: 'Upload CSV or Excel file with recipients details',
            upload_instruction: 'Click to upload or drag and drop',
            file_types_supported: 'CSV, XLSX or XLS files supported',
            display_name: 'Display Name',
            mobile_phone: 'Mobile Phone',
            clear: 'Clear',
            import_recipients_count: 'Import {count} Recipients',
            name_english: 'Name (English)',
            name_gujarati: 'Name (Gujarati)',
            converting: 'Converting...',
            auto_convert: 'Auto Convert',
            mobile_number: 'Mobile Number',
            village_english: 'Village (English)',
            village_gujarati: 'Village (Gujarati)',
            send_invitation: 'Send Invitation',
            to: 'To',
            select_template: 'Select Document Template',
            loading: 'Loading',
            no_templates_found: 'No active documents found. Please create one first.',
            gujarati: 'Gujarati',
            english: 'English',
            live_preview: 'Live Preview',
            personalization_active: 'Personalization Active',
            details_will_appear: "The recipient's details (name, village, etc.) will appear exactly as shown in the preview above across {count} positions.",
            send_whatsapp: 'Send via WhatsApp',
            add_from_contacts: 'Add from Contacts',
            contacts_selected: '{count} contact(s) selected — review before adding',
            will_be_added: 'will be added',
            no_links_generated: 'No links generated yet for this recipient.',
            generate_first_link: 'Generate First Link',
            unknown_document: 'Unknown Document',
            created_on: 'Created on {date}',
            copied: 'Copied',
            copy: 'Copy',
            close: 'Close',
            import: 'Import',
            preview: 'Preview'
        },
        gu: {
            dashboard: 'ડેશબોર્ડ',
            documents: 'દસ્તાવેજો',
            recipients: 'લેનારાઓ',
            analytics: 'એનાલિટિક્સ',
            subscription: 'સબ્સ્બ્ક્રિપ્શન',
            settings: 'સેટિંગ્સ',
            users: 'વપરાશકર્તાઓ',
            sign_out: 'સાઇન આઉટ',
            new_document: 'નવો દસ્તાવેજ',
            notifications: 'સૂચનાઓ',
            search: 'શોધો',
            welcome_back: 'સ્વાગત છે',
            admin: 'એડમિન',
            super_admin: 'સુપર એડમિન',
            member: 'સભ્ય',
            village_name: 'ગામનું નામ',
            recipient_name: 'નામ',
            edit_document: 'દસ્તાવેજ સંપાદિત કરો',
            create_document: 'દસ્તાવેજ બનાવો',
            home: 'હોમ',
            publish_document: 'દસ્તાવેજ પ્રકાશિત કરો',
            save_as_draft: 'ડ્રાફ્ટ તરીકે સાચવો',
            back_to_editor: 'એડિટર પર પાછા જાઓ',
            review_confirm: 'સમીક્ષા અને પુષ્ટિ',
            details: 'વિગતો',
            upload: 'અપલોડ કરો',
            fields: 'ફીલ્ડ્સ',
            review: 'સમીક્ષા',
            name_your_document: 'તમારા દસ્તાવેજનું નામ આપો',
            document_title: 'દસ્તાવેજનું શીર્ષક',
            description: 'વર્ણન',
            continue: 'આગળ વધો',
            cancel: 'રદ કરો',
            drop_files_here: 'ફાઇલો અહીં મૂકો',
            choose_files: 'ફાઇલો પસંદ કરો',
            uploaded_document: 'અપલોડ કરેલ દસ્તાવેજ',
            add_fields: 'ફીલ્ડ્સ ઉમેરો',
            placed_fields: 'મૂકેલી ફીલ્ડ્સ',
            width: 'પહોળાઈ',
            height: 'ઊંચાઈ',
            color: 'રંગ',
            language_selection: 'ભાષા પસંદગી',
            add_recipient: 'લેનાર ઉમેરો',
            edit_recipient: 'લેનાર સુધારો',
            import_recipients: 'લેનારાઓ આયાત કરો',
            export: 'નિકાસ',
            search_recipients: 'લેનારાઓ શોધો...',
            all_recipients: 'બધા લેનારાઓ',
            active: 'સક્રિય',
            inactive: 'નિષ્ક્રિય',
            name: 'નામ',
            village: 'ગામ',
            phone: 'ફોન',
            actions: 'ક્રિયાઓ',
            edit: 'સંપાદિત કરો',
            delete: 'કાઢી નાખો',
            save_changes: 'ફેરફારો સાચવો',
            total_recipients: 'કુલ લેનારાઓ',
            links_sent: 'મોકલેલ લિંક્સ',
            pending: 'બાકી',
            sent: 'મોકલેલ',
            all_villages: 'બધા ગામો',
            opening: 'ખુલી રહ્યું છે...',
            from_contacts: 'કોન્ટેક્ટ્સ માંથી',
            recent_activity: 'તાજેતરની પ્રવૃત્તિ',
            view_all: 'બધું જુઓ',
            status: 'સ્થિતિ',
            selected: 'પસંદ કરેલ',
            send_whatsapp_all: 'બધાને વોટ્સએપ મોકલો',
            generate_links: 'લિંક્સ બનાવો',
            delete_selected: 'પસંદ કરેલ કાઢી નાખો',
            update_recipient: 'લેનાર અપડેટ કરો',
            total_documents: 'કુલ દસ્તાવેજો',
            in_progress: 'ચાલુ છે',
            completed: 'પૂર્ણ',
            drafts: 'ડ્રાફ્ટ',
            search_documents: 'દસ્તાવેજો શોધો...',
            all_statuses: 'બધી સ્થિતિઓ',
            draft: 'ડ્રાફ્ટ',
            expired: 'સમાપ્ત',
            title: 'શીર્ષક',
            progress: 'પ્રગતિ',
            date: 'તારીખ',
            no_description: 'કોઈ વર્ણન નથી',
            no_documents_found: 'કોઈ દસ્તાવેજો મળ્યા નથી',
            create_first_document: 'શરૂ કરવા માટે તમારો પહેલો દસ્તાવેજ બનાવો.',
            delete_document: 'દસ્તાવેજ કાઢી નાખો',
            action_cannot_undone: 'આ ક્રિયા પાછી ખેંચી શકાતી નથી',
            view: 'જુઓ',
            create: 'બનાવો',
            document_name_desc: 'સરળ ટ્રેકિંગ માટે તમારા દસ્તાવેજને સ્પષ્ટ શીર્ષક આપો.',
            optional: 'વૈકલ્પિક',
            description_placeholder: 'આ દસ્તાવેજ માટે થોડી વિગતો ઉમેરો...',
            upload_desc: 'અથવા બ્રાઉઝ કરવા માટે ક્લિક કરો — PDF અથવા છબીઓ સપોર્ટેડ છે',
            uploaded: 'અપલોડ કરેલ',
            page: 'પાનું',
            add_fields_desc: 'જ્યાં લેનારાઓએ તેમની માહિતી આપવાની હોય ત્યાં ફીલ્ડ્સ મૂકવા માટે દસ્તાવેજ પર ક્લિક કરો.',
            preparing: 'તૈયાર કરી રહ્યું છે...',
            download: 'ડાઉનલોડ કરો',
            access_denied: 'પ્રવેશ નકારવામાં આવ્યો',
            expired_link_desc: 'આ આમંત્રણ લિંક સમાપ્ત થઈ ગઈ છે અથવા સુરક્ષા ટોકન અમાન્ય છે. કૃપા કરીને નવી લિંક માટે મોકલનારનો સંપર્ક કરો.',
            go_to_homepage: 'હોમપેજ પર જાઓ',
            personal_invitation: 'વ્યક્તિગત આમંત્રણ',
            loading_invitation: 'તમારું આમંત્રણ લોડ થઈ રહ્યું છે...',
            document_unavailable: 'દસ્તાવેજ ઉપલબ્ધ નથી.',
            namaste: 'નમસ્તે',
            invited_from: 'તમને અમારી સાથે જોડાવા માટે આમંત્રણ આપવામાં આવ્યું છે',
            analytics_desc: 'તમારા આમંત્રણના પ્રદર્શનને ટ્રૅક કરો',
            last_7_days: 'છેલ્લા ૭ દિવસ',
            last_30_days: 'છેલ્લા ૩૦ દિવસ',
            last_90_days: 'છેલ્લા ૯૦ દિવસ',
            documents_created: 'બનાવેલ દસ્તાવેજો',
            links_generated: 'બનાવેલ લિંક્સ',
            whatsapp_sent: 'મોકલેલ વોટ્સએપ',
            email_sent: 'મોકલેલ ઈમેલ',
            links_generated_over_time: 'સમય જતાં બનેલી લિંક્સ',
            links: 'લિંક્સ',
            whatsapp: 'વોટ્સએપ',
            top_documents: 'ટોચના દસ્તાવેજો',
            delivery_channels: 'વિતરણ માધ્યમો',
            village_breakdown: 'ગામ મુજબ વિગતો',
            admin_greeting: 'સ્વાગત છે, એડમિન!',
            dashboard_subtitle: 'તમારા આમંત્રણો સાથે આજે શું થઈ રહ્યું છે તે અહીં છે.',
            recent_documents: 'તાજેતરના દસ્તાવેજો',
            manage_subscription: 'સબ્સ્ક્રિપ્શન મેનેજ કરો',
            upload_template: 'ટેમ્પલેટ અપલોડ કરો',
            add_new_document: 'નવો દસ્તાવેજ ઉમેરો',
            add_recipients: 'લેનારા ઉમેરો',
            edit_recipients: 'લેનાર સુધારો',
            manage_your_list: 'તમારી યાદી મેનેજ કરો',
            send_via_whatsapp: 'વોટ્સએપ દ્વારા મોકલો',
            share_invitations: 'આમંત્રણો શેર કરો',
            view_analytics: 'એનાલિટિક્સ જુઓ',
            track_performance: 'પ્રદર્શન ટ્રૅક કરો',
            import_desc: 'લેનારાઓની વિગતો સાથે CSV અથવા Excel ફાઇલ અપલોડ કરો',
            upload_instruction: 'અપલોડ કરવા માટે ક્લિક કરો અથવા ખેંચો અને મૂકો',
            file_types_supported: 'CSV, XLSX અથવા XLS ફાઇલો સપોર્ટેડ છે',
            display_name: 'નામ',
            mobile_phone: 'મોબાઇલ ફોન',
            clear: 'સાફ કરો',
            import_recipients_count: '{count} લેનારાઓ આયાત કરો',
            name_english: 'નામ (અંગ્રેજી)',
            name_gujarati: 'નામ (ગુજરાતી)',
            converting: 'રૂપાંતરિત થઈ રહ્યું છે...',
            auto_convert: 'ઓટો કન્વર્ટ',
            mobile_number: 'મોબાઇલ નંબર',
            village_english: 'ગામ (અંગ્રેજી)',
            village_gujarati: 'ગામ (ગુજરાતી)',
            send_invitation: 'આમંત્રણ મોકલો',
            to: 'પ્રતિ',
            select_template: 'દસ્તાવેજ ટેમ્પલેટ પસંદ કરો',
            loading: 'લોડ થઈ રહ્યું છે',
            no_templates_found: 'કોઈ સક્રિય દસ્તાવેજો મળ્યા નથી. કૃપા કરીને પહેલા એક બનાવો.',
            gujarati: 'ગુજરાતી',
            english: 'અંગ્રેજી',
            live_preview: 'લાઇવ પ્રિવ્યૂ',
            personalization_active: 'વૈયક્તિકરણ સક્રિય',
            details_will_appear: "લેનારની વિગતો (નામ, ગામ, વગેરે) {count} જગ્યાઓ પર ઉપરના પ્રિવ્યૂમાં બતાવ્યા પ્રમાણે દેખાશે.",
            send_whatsapp: 'વોટ્સએપ દ્વારા મોકલો',
            add_from_contacts: 'કોન્ટેક્ટ્સ માંથી ઉમેરો',
            contacts_selected: '{count} કોન્ટેક્ટ પસંદ કરેલ — ઉમેરતા પહેલા સમીક્ષા કરો',
            will_be_added: 'ઉમેરવામાં આવશે',
            no_links_generated: 'આ લેનાર માટે હજી સુધી કોઈ લિંક્સ જનરેટ થઈ નથી.',
            generate_first_link: 'પ્રથમ લિંક બનાવો',
            unknown_document: 'અજ્ઞાત દસ્તાવેજ',
            created_on: '{date} ના રોજ બનાવેલ',
            copied: 'કોપી કરેલ',
            copy: 'કોપી કરો',
            close: 'બંધ કરો',
            import: 'આયાત કરો',
            preview: 'પ્રિવ્યૂ'
        }
    });

    const setLocale = (locale) => {
        if (translations.value[locale]) {
            currentLocale.value = locale;
            localStorage.setItem('locale', locale);
            document.documentElement.lang = locale;
        }
    };

    const t = (key, params = {}) => {
        let text = translations.value[currentLocale.value][key] || key;
        Object.keys(params).forEach(p => {
            text = text.replace(`{${p}}`, params[p]);
        });
        return text;
    };

    return {
        currentLocale,
        locales,
        setLocale,
        t
    };
});
